[package]
name = "scrape-rs"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "A small multithreaded web scraping library: concurrent fetching with a shared connection pool and CSS-selector HTML parsing."
readme = "../README.md"
repository = "https://github.com/amogus-gggy/scrape-rs"

[dependencies]
ureq = { version = "3.4.0", features = ["charset"] }
scraper = "0.20"
uuid = { version = "1.24.1", features = ["v4"] }
thiserror = "1.0"
dhat = "0.3.3"

[features]
dhat-heap = []
